### ISSUE TITLE
FYI this is how I'm using your repo

### ISSUE THREAD

**Issue by joepalermo** [ankitaggarwal011/MNIST-Sequence#1]
Hey Ankit, 

Thanks for your work. I'm using it to generate training data for some ML experiments.

FYI this is how I'm using it. Maybe you want to add a utility like this:

https://github.com/jwpalermo28/image-captioning/blob/master/mnist-sequences/generate_mnist_sequences.py

**Comment by ankitaggarwal011** [comment]
@jwpalermo28, this is great. I'm glad that my code was helpful in your project. Thank you for informing me about this. All the best!

Would you please consider contributing your utility to this project? I'm sure it would be helpful for others as well.

**Comment by joepalermo** [comment]
Oh hey, thanks for adding this. Sorry I never got around to it.
